### ISSUE TITLE
Tickets - June Version

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-website-2019#8]
### Tickets
Ideas that needs discussion to clarify what we want and can achieve for June version.

**Questions/Ideas**
how are we selling tickets?
where will users go to buy tickets? (external button links or modal on page)
who is writing ticket content and tiers?
when will content/decisions be completed by? (to be live by june?)
________________________________
### Draft Wireframe
Content for placement only.
<img width="300" src=https://user-images.githubusercontent.com/2492510/55363271-5c79fb80-5491-11e9-8d33-e11858ce211b.png>

**Comment by beccaklam** [comment]
@gideonthomas Can you confirm if we are using tito for ticket sales?

**Comment by gideonthomas** [comment]
yeah we're using Ti.To

**Comment by beccaklam** [comment]
Sweet thanks. @alanmoo this is a [wireframe](https://redpen.io/vy1d8f50e4c69ff620) of what we're thinking for the tickets page on the mozfest site. @sabrinang said all they did last year was embed the Ti.To button on the page and it would launch a light box. Would this be feasible for this year?

**Comment by alanmoo** [comment]
Most things are feasible, but this is the type of thing where it might be helpful to have a higher level overview of the work that needs to be done so we can have a conversation about what's reasonable to implement within the tight timeframe.

The ideal for the site is that we build a nav/footer/header(?) and can use existing streamfield components from the main Foundation site to put together the core of all the pages. If we need to build another component or two (social embed, for example), that's fine because we can re-use it on the Foundation site later too. So this example would be easier if the repeated blocks are already a component, and the link is simply a URL that triggers the lightbox. That being said, I'm guessing there will need to be some extra work done to make those functional and having an understanding of the overall lift for the site helps understand how elegant of a solution we can make it.

(Sorry for a non-answer, feel free to schedule a meeting to talk over wireframes at a higher level)

**Comment by sabrinang** [comment]
Confirm with Zannah that tickets will be an external page so we will have an external link to a tito page with all our ticket options ([2017 tito example page](https://ti.to/Mozilla/mozfest-2017))

**Comment by gideonthomas** [comment]
@sabrinang just to clarify: engineers will try to embed the ticket purchase in the site, but we're unsure if it will be done in time...hence, the fallback is that we create a page on Ti.To with all the ticketing options. Right?

**Comment by sabrinang** [comment]
@gideonthomas hmm good point, I'm unsure of the status of ticket widget https://github.com/mozilla/foundation.mozilla.org/issues/3121 or if we are just going with external page

**Comment by sabrinang** [comment]
Note: if page is external, it'll be an external nav link
<img width="956" alt="image" src="https://user-images.githubusercontent.com/2492510/57737464-a6ddc300-7660-11e9-9977-c1a251539e13.png">

**Comment by Pomax** [comment]
For the actual "buy ticket" block presentation/placement on the page we can use streamfields (using sets of {image+text component, linkbutton component, spacer component} which gets us pretty close to the comps without requiring additional time for dev/iteration cycles.

**Comment by gideonthomas** [comment]
@sabrinang good to close?
